"""
Electron Framework Adapter for Reviewer Test Harness (Architecture H).
Generates in-process dev client hooks and surgical entry-point injection
for Electron applications without compromising Chromium or Node sandbox security.
"""

from __future__ import annotations
import json
from typing import Dict, Any, Tuple

from runtime.capability import CapabilityStatus
from runtime.harness.adapters.base import BaseHarnessAdapter


class ElectronHarnessAdapter(BaseHarnessAdapter):
    """
    Adapter for Electron desktop applications.
    Hooks into Electron app/window events and communicates with Reviewer Harness transport.
    """

    @property
    def adapter_name(self) -> str:
        return "electron"

    @property
    def framework(self) -> str:
        return "electron"

    def get_supported_capabilities(self) -> Dict[str, CapabilityStatus]:
        return {
            "lifecycle": CapabilityStatus.AVAILABLE,
            "diagnostics": CapabilityStatus.AVAILABLE,
            "fixtures": CapabilityStatus.AVAILABLE,
            "fault_injection": CapabilityStatus.AVAILABLE,
        }

    def get_dev_marker_pair(self) -> Tuple[str, str]:
        return (
            "/* REVIEWER_HARNESS_DEV_ONLY_BEGIN */",
            "/* REVIEWER_HARNESS_DEV_ONLY_END */",
        )

    def get_injection_snippet(self, client_rel_path: str = "./reviewer_harness.dev.js") -> str:
        begin, end = self.get_dev_marker_pair()
        # Normalize relative path for require
        clean_path = client_rel_path.replace("\\", "/")
        if not clean_path.startswith("."):
            clean_path = f"./{clean_path}"
        return f"""{begin}
if (process.env.NODE_ENV !== 'production') {{
  try {{
    const {{ initReviewerHarness }} = require('{clean_path}');
    initReviewerHarness();
  }} catch (e) {{
    // Reviewer harness is optional in development
  }}
}}
{end}"""

    def generate_harness_client_file(self, project_path: str, config: Dict[str, Any]) -> Tuple[str, str]:
        rel_filename = "reviewer_harness.dev.js"
        session_id = config.get("session_id", "dev_session")
        app_id = config.get("app_id", "electron_app")
        default_port = config.get("port", 9444)
        auth_token = config.get("auth_token", "")

        js_content = f"""/**
 * Reviewer Test Harness — In-Process Diagnostic Client (Development Build Only).
 * AUTO-GENERATED BY DESKTOP WEBVIEW REVIEWER.
 * This file is strictly excluded from release/production builds.
 */

'use strict';

const http = require('http');
const {{ app, BrowserWindow }} = require('electron');

const HARNESS_CONFIG = {{
  sessionId: process.env.REVIEWER_HARNESS_SESSION_ID || {json.dumps(session_id)},
  appId: process.env.REVIEWER_HARNESS_APP_ID || {json.dumps(app_id)},
  port: parseInt(process.env.REVIEWER_HARNESS_PORT || '{default_port}', 10),
  token: process.env.REVIEWER_HARNESS_TOKEN || {json.dumps(auth_token)},
  instanceId: 'inst_' + Math.random().toString(36).substring(2, 10),
}};

let _sequence = 0;

function sendHarnessMessage(type, payload) {{
  if (process.env.NODE_ENV === 'production') return Promise.resolve({{}});
  
  _sequence++;
  const body = JSON.stringify({{
    session_id: HARNESS_CONFIG.sessionId,
    application_id: HARNESS_CONFIG.appId,
    harness_instance_id: HARNESS_CONFIG.instanceId,
    message_type: type,
    payload: payload || {{}},
    sequence: _sequence,
    auth_token: HARNESS_CONFIG.token,
    timestamp: Date.now() / 1000.0,
  }});

  return new Promise((resolve) => {{
    const req = http.request({{
      hostname: '127.0.0.1',
      port: HARNESS_CONFIG.port,
      path: '/harness/v1/' + type.toLowerCase(),
      method: 'POST',
      headers: {{
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body),
        'X-Reviewer-Harness-Token': HARNESS_CONFIG.token,
      }},
      timeout: 1500,
    }}, (res) => {{
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {{
        try {{ resolve(JSON.parse(data)); }} catch (e) {{ resolve({{ status: 'OK' }}); }}
      }});
    }});

    req.on('error', () => resolve({{ status: 'UNREACHABLE' }}));
    req.on('timeout', () => {{ req.destroy(); resolve({{ status: 'TIMEOUT' }}); }});
    req.write(body);
    req.end();
  }});
}}

function emitLifecycle(signal, details) {{
  return sendHarnessMessage('LIFECYCLE', {{ signal, details: details || {{}} }});
}}

function emitDiagnostics(diagnostics) {{
  return sendHarnessMessage('DIAGNOSTICS', {{ diagnostics: diagnostics || {{}} }});
}}

function initReviewerHarness() {{
  if (process.env.NODE_ENV === 'production') return;

  // 1. Send Handshake
  sendHarnessMessage('HANDSHAKE', {{
    capabilities: {{
      lifecycle: 'AVAILABLE',
      diagnostics: 'AVAILABLE',
      fixtures: 'AVAILABLE',
      fault_injection: 'AVAILABLE',
    }}
  }});

  // 2. Hook App Lifecycle
  emitLifecycle('APP_STARTING', {{ process_id: process.pid }});

  const onReady = () => {{
    emitLifecycle('APP_READY', {{
      electron_version: process.versions.electron,
      chrome_version: process.versions.chrome,
    }});
  }};

  if (app.isReady()) {{
    onReady();
  }} else {{
    app.once('ready', onReady);
  }}

  // 3. Hook Window & WebContents Lifecycle
  app.on('browser-window-created', (event, win) => {{
    if (!win || !win.webContents) return;

    win.webContents.on('did-start-navigation', (e, url) => {{
      emitLifecycle('NAVIGATION_STARTED', {{ url }});
    }});

    win.webContents.on('did-navigate', (e, url) => {{
      emitLifecycle('NAVIGATION_COMPLETED', {{ url }});
    }});

    win.webContents.on('did-finish-load', () => {{
      emitLifecycle('SCREEN_READY', {{ title: win.getTitle() }});
    }});
  }});
}}

module.exports = {{
  initReviewerHarness,
  emitLifecycle,
  emitDiagnostics,
  sendHarnessMessage,
}};
"""
        return (rel_filename, js_content)
