"""
Qt / QtWebEngine Framework Adapter for Reviewer Test Harness (Architecture H).
Generates in-process PyQt/PySide hooks and surgical integration for Qt applications.
Preserves strict separation between application diagnostic telemetry and Reviewer's CDP plane.
"""

from __future__ import annotations
import json
from typing import Dict, Any, Tuple

from runtime.capability import CapabilityStatus
from runtime.harness.adapters.base import BaseHarnessAdapter


class QtHarnessAdapter(BaseHarnessAdapter):
    """
    Adapter for PyQt / PySide + QtWebEngine desktop applications.
    Hooks into Qt event loop and QWebEnginePage/View lifecycle signals.
    """

    @property
    def adapter_name(self) -> str:
        return "qtwebengine"

    @property
    def framework(self) -> str:
        return "qt"

    def get_supported_capabilities(self) -> Dict[str, CapabilityStatus]:
        return {
            "lifecycle": CapabilityStatus.AVAILABLE,
            "diagnostics": CapabilityStatus.AVAILABLE,
            "fixtures": CapabilityStatus.AVAILABLE,
            "fault_injection": CapabilityStatus.AVAILABLE,
        }

    def get_dev_marker_pair(self) -> Tuple[str, str]:
        return (
            "# REVIEWER_HARNESS_DEV_ONLY_BEGIN",
            "# REVIEWER_HARNESS_DEV_ONLY_END",
        )

    def get_injection_snippet(self, client_rel_path: str = "reviewer_harness_qt.py") -> str:
        begin, end = self.get_dev_marker_pair()
        module_name = client_rel_path.replace(".py", "").replace("/", ".").replace("\\", ".")
        return f"""{begin}
import os as _os
if _os.environ.get("BUILD_MODE") != "RELEASE":
    try:
        from {module_name} import init_reviewer_harness as _init_harness
        _init_harness()
    except Exception:
        pass
{end}"""

    def generate_harness_client_file(self, project_path: str, config: Dict[str, Any]) -> Tuple[str, str]:
        rel_filename = "reviewer_harness_qt.py"
        session_id = config.get("session_id", "dev_session")
        app_id = config.get("app_id", "qt_app")
        default_port = config.get("port", 9444)
        auth_token = config.get("auth_token", "")

        py_content = f'''"""
Reviewer Test Harness — In-Process Diagnostic Client for Qt / QtWebEngine.
AUTO-GENERATED BY DESKTOP WEBVIEW REVIEWER.
Strictly excluded from release production builds.
"""

import json
import os
import secrets
import sys
import threading
import time
import urllib.request

HARNESS_CONFIG = {{
    "session_id": os.environ.get("REVIEWER_HARNESS_SESSION_ID", {json.dumps(session_id)}),
    "app_id": os.environ.get("REVIEWER_HARNESS_APP_ID", {json.dumps(app_id)}),
    "port": int(os.environ.get("REVIEWER_HARNESS_PORT", "{default_port}")),
    "token": os.environ.get("REVIEWER_HARNESS_TOKEN", {json.dumps(auth_token)}),
    "instance_id": "inst_" + secrets.token_hex(4),
}}

_sequence = 0
_lock = threading.Lock()


def send_harness_message(message_type: str, payload: dict = None) -> dict:
    global _sequence
    if os.environ.get("BUILD_MODE") == "RELEASE":
        return {{}}

    with _lock:
        _sequence += 1
        seq = _sequence

    body = {{
        "session_id": HARNESS_CONFIG["session_id"],
        "application_id": HARNESS_CONFIG["app_id"],
        "harness_instance_id": HARNESS_CONFIG["instance_id"],
        "message_type": message_type,
        "payload": payload or {{}},
        "sequence": seq,
        "auth_token": HARNESS_CONFIG["token"],
        "timestamp": time.time(),
    }}

    data = json.dumps(body).encode("utf-8")
    url = f"http://127.0.0.1:{{HARNESS_CONFIG['port']}}/harness/v1/{{message_type.lower()}}"
    req = urllib.request.Request(
        url,
        data=data,
        headers={{
            "Content-Type": "application/json",
            "X-Reviewer-Harness-Token": HARNESS_CONFIG["token"],
        }},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=1.5) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception:
        return {{"status": "UNREACHABLE"}}


def emit_lifecycle(signal: str, details: dict = None) -> dict:
    return send_harness_message("LIFECYCLE", {{"signal": signal, "details": details or {{}}}})


def emit_diagnostics(diagnostics: dict) -> dict:
    return send_harness_message("DIAGNOSTICS", {{"diagnostics": diagnostics or {{}}}})


def init_reviewer_harness():
    if os.environ.get("BUILD_MODE") == "RELEASE":
        return

    threading.Thread(target=_background_init, daemon=True).start()


def _background_init():
    send_harness_message("HANDSHAKE", {{
        "capabilities": {{
            "lifecycle": "AVAILABLE",
            "diagnostics": "AVAILABLE",
            "fixtures": "AVAILABLE",
            "fault_injection": "AVAILABLE",
        }}
    }})
    emit_lifecycle("APP_STARTING", {{"pid": os.getpid()}})
    emit_lifecycle("APP_READY", {{"platform": sys.platform}})
'''
        return (rel_filename, py_content)
