"""
WebView2 Framework Adapter for Reviewer Test Harness (Architecture H).
Generates in-process C# host hooks and surgical integration for WebView2 hosts
(WPF, WinForms, WinUI 3) with preprocessor build segregation (#if DEBUG).
"""

from __future__ import annotations
import json
from typing import Dict, Any, Tuple

from runtime.capability import CapabilityStatus
from runtime.harness.adapters.base import BaseHarnessAdapter


class WebView2HarnessAdapter(BaseHarnessAdapter):
    """
    Adapter for Microsoft WebView2 desktop hosts.
    Hooks into CoreWebView2 initialization and navigation lifecycle events.
    """

    @property
    def adapter_name(self) -> str:
        return "webview2"

    @property
    def framework(self) -> str:
        return "webview2"

    def get_supported_capabilities(self) -> Dict[str, CapabilityStatus]:
        return {
            "lifecycle": CapabilityStatus.AVAILABLE,
            "diagnostics": CapabilityStatus.AVAILABLE,
            "fixtures": CapabilityStatus.AVAILABLE,
            "fault_injection": CapabilityStatus.DEGRADED,
        }

    def get_dev_marker_pair(self) -> Tuple[str, str]:
        return (
            "/* REVIEWER_HARNESS_DEV_ONLY_BEGIN */",
            "/* REVIEWER_HARNESS_DEV_ONLY_END */",
        )

    def get_injection_snippet(self, client_rel_path: str = "ReviewerHarness.cs") -> str:
        begin, end = self.get_dev_marker_pair()
        return f"""{begin}
#if DEBUG || REVIEWER_HARNESS
ReviewerHarness.Initialize(this);
#endif
{end}"""

    def generate_harness_client_file(self, project_path: str, config: Dict[str, Any]) -> Tuple[str, str]:
        rel_filename = "ReviewerHarness.cs"
        session_id = config.get("session_id", "dev_session")
        app_id = config.get("app_id", "webview2_app")
        default_port = config.get("port", 9444)
        auth_token = config.get("auth_token", "")

        cs_content = f"""// <auto-generated>
// Reviewer Test Harness — In-Process Diagnostic Client for WebView2.
// AUTO-GENERATED BY DESKTOP WEBVIEW REVIEWER.
// Excluded from release builds via preprocessor directives.
// </auto-generated>

#if DEBUG || REVIEWER_HARNESS

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

public static class ReviewerHarness
{{
    private static readonly HttpClient _httpClient = new HttpClient();
    private static string _sessionId = Environment.GetEnvironmentVariable("REVIEWER_HARNESS_SESSION_ID") ?? {json.dumps(session_id)};
    private static string _appId = Environment.GetEnvironmentVariable("REVIEWER_HARNESS_APP_ID") ?? {json.dumps(app_id)};
    private static int _port = int.TryParse(Environment.GetEnvironmentVariable("REVIEWER_HARNESS_PORT"), out var p) ? p : {default_port};
    private static string _token = Environment.GetEnvironmentVariable("REVIEWER_HARNESS_TOKEN") ?? {json.dumps(auth_token)};
    private static string _instanceId = "inst_" + Guid.NewGuid().ToString("N").Substring(0, 8);
    private static int _sequence = 0;

    public static async Task SendMessageAsync(string messageType, object payload)
    {{
        try
        {{
            _sequence++;
            var bodyObj = new Dictionary<string, object>
            {{
                ["session_id"] = _sessionId,
                ["application_id"] = _appId,
                ["harness_instance_id"] = _instanceId,
                ["message_type"] = messageType,
                ["payload"] = payload ?? new Dictionary<string, object>(),
                ["sequence"] = _sequence,
                ["auth_token"] = _token,
                ["timestamp"] = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() / 1000.0,
            }};

            var json = JsonSerializer.Serialize(bodyObj);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            content.Headers.Add("X-Reviewer-Harness-Token", _token);

            var url = $"http://127.0.0.1:{{_port}}/harness/v1/{{messageType.ToLowerInvariant()}}";
            await _httpClient.PostAsync(url, content);
        }}
        catch
        {{
            // Harness is diagnostic and test-support only; never crash host app.
        }}
    }}

    public static Task EmitLifecycleAsync(string signal, object details = null)
    {{
        return SendMessageAsync("LIFECYCLE", new Dictionary<string, object>
        {{
            ["signal"] = signal,
            ["details"] = details ?? new Dictionary<string, object>()
        }});
    }}

    public static Task EmitDiagnosticsAsync(object diagnostics)
    {{
        return SendMessageAsync("DIAGNOSTICS", new Dictionary<string, object>
        {{
            ["diagnostics"] = diagnostics ?? new Dictionary<string, object>()
        }});
    }}

    public static void Initialize(object hostContext)
    {{
        Task.Run(async () =>
        {{
            await SendMessageAsync("HANDSHAKE", new Dictionary<string, object>
            {{
                ["capabilities"] = new Dictionary<string, string>
                {{
                    ["lifecycle"] = "AVAILABLE",
                    ["diagnostics"] = "AVAILABLE",
                    ["fixtures"] = "AVAILABLE",
                    ["fault_injection"] = "DEGRADED"
                }}
            }});
            await EmitLifecycleAsync("APP_STARTING");
            await EmitLifecycleAsync("APP_READY");
        }});
    }}
}}

#endif
"""
        return (rel_filename, cs_content)
